var languages = {
    "en": {
        language: "English",
        menuNoStartSwap: "Maiden first",
        menuFirstPlayer: "First player: ",
        menuSecondPlayer: "Second player: ",
        menuGame: "Game: ",
        menuSets: "Sets: ",
        menuLegs: "Legs: ",
        menuNewGame: "New Game",
        menuContinue: "Continue",
        menuHistory: "History",
        menuMenu: "Close",
        histoyTotal: "Total: ",
        keyboardMenu: "M",
        keyboardOk: "Ok",
        set: "Set ",
        leg: "Leg ",
        sets: "Sets",
        legs: "Legs",
        bannerInstall: "Istall Application",
        bannerDescription: "Add the Darts Forge application to your home screen",
        menuProfile: "User profile",
        menuPublicKey: "Public key",
        menuPrivateKey: "Private key",
        menuLoginSignin: "Log In | Sign In",
        menuLogout: "Log Out"
    },
    "ru": {
        language: "Русский",
        menuNoStartSwap: "Maiden first",
        menuFirstPlayer: "Первый игрок: ",
        menuSecondPlayer: "Второй игрок: ",
        menuGame: "Игра: ",
        menuSets: "Сетов: ",
        menuLegs: "Легов: ",
        menuNewGame: "Новая игра",
        menuContinue: "Продолжить",
        menuHistory: "История",
        menuMenu: "Закрыть",
        histoyTotal: "Всего: ",
        keyboardMenu: "М",
        keyboardOk: "Ok",
        set: "Сет ",
        leg: "Лег ",
        sets: "Sets",
        legs: "Legs",
        bannerInstall: "Установить приложение",
        bannerDescription: "Добавить приложение Darts Forge на рабочий стол",
        menuProfile: "Профиль пользователя",
        menuPublicKey: "Публичный ключ",
        menuPrivateKey: "Секретный ключ",
        menuLoginSignin: "Войти",
        menuLogout: "Выйти"
    }

};