var languages = {
    "en": {
        flag: "flag-GB",
        language: "English",
        menuNoStartSwap: "Maiden first",
        menuFirstPlayer: "First player: ",
        menuSecondPlayer: "Second player: ",
        menuGame: "Game: ",
        menuSets: "Sets: ",
        menuLegs: "Legs: ",
        menuNewGame: "New Game",
        menuContinue: "Continue",
        menuHistory: "History",
        menuMenu: "Close",
        histoyTotal: "Total: ",
        keyboardMenu: "M",
        keyboardOk: "Ok",
        set: "Set ",
        leg: "Leg ",
        sets: "Sets",
        legs: "Legs",
        bannerInstall: "Istall Application",
        bannerDescription: "Add the Darts Forge application to your home screen",
        menuProfile: "User profile",
        menuPublicKey: "Public key",
        menuPrivateKey: "Private key",
        menuLoginSignin: "Log In | Sign In",
        menuLogout: "Log Out",
        menuSelectCommunity: "Select Community",
        menuInCommunity: " at ",
        communities: "Communities: ",
        refresh: "Refresh",
        createCommunity: "Create community",
        createCommunityBtn: "Create",
        createCommunityCity: "City",
        createCommunityName: "Community Name",
        changeCommunity: "Change community",
        courtCommunity: "Court the community",
        selectCommunityName: "Select community",
        courtCommunityBtn: "Court",
        ownedCommunities: "Your communities",
        joinedCommunities: "Joined communities",
        courtedCommunities: "Waiting agreement",
        communityCreated: "Community created!",
        changeCommunityBtn: "Change",
        communitiesNews: "Events",
        reject: "Reject",
        apply: "Apply",
        courtMessage1: "You courted the ",
        courtMessage2: " but the application is not approoved yet",
        joinMessage1: " wants to join to the ",
        joinMessage2: ". You can apply or reject the application",
        menuChangeCommunity: "change",
        menuSettings: "Settings",
        menuSelectEnding: "Endings",
        menuSelectLanguage: "Language",
        communityRating: "Rating",
        communityCourted: "You courted the community. Wait approovement please.",
        userOwner: "Owner",
        userReferee: "Referee",
        userPlayer: "Player",
        menuMarkerView: "Marker",
        menuCommunityEvents: "Events",
        createCommunityEvent: "Event name",
        createCommunityEventBtn: "Create",
        menuCommunityEventsNew: "Create new event",
        communityEventCreated: "Event created",
        activeEvent: "Active",
        inactiveEvent: "Finished"
    },
    "ru": {
        flag: "flag-RU",
        language: "Русский",
        menuNoStartSwap: "Maiden first",
        menuFirstPlayer: "Первый игрок: ",
        menuSecondPlayer: "Второй игрок: ",
        menuGame: "Игра: ",
        menuSets: "Сетов: ",
        menuLegs: "Легов: ",
        menuNewGame: "Новая игра",
        menuContinue: "Продолжить",
        menuHistory: "История",
        menuMenu: "Закрыть",
        histoyTotal: "Всего: ",
        keyboardMenu: "М",
        keyboardOk: "Ok",
        set: "Сет ",
        leg: "Лег ",
        sets: "Sets",
        legs: "Legs",
        bannerInstall: "Установить приложение",
        bannerDescription: "Добавить приложение Darts Forge на рабочий стол",
        menuProfile: "Профиль пользователя",
        menuPublicKey: "Публичный ключ",
        menuPrivateKey: "Секретный ключ",
        menuLoginSignin: "Войти",
        menuLogout: "Выйти",
        menuSelectCommunity: "Выберите Сообщество",
        menuInCommunity: " в ",
        communities: "Сообщества: ",
        refresh: "Обновить",
        createCommunity: "Создать сообщество",
        createCommunityBtn: "Создать",
        createCommunityCity: "Город",
        createCommunityName: "Название",
        changeCommunity: "Сменить сообщество",
        courtCommunity: "Вступить в сообщество",
        selectCommunityName: "Выберите сообщество",
        courtCommunityBtn: "Вступить",
        ownedCommunities: "Ваши сообщества",
        joinedCommunities: "Одобренные сообщества",
        courtedCommunities: "Ожидают одобрения",
        communityCreated: "Сообщество создано!",
        changeCommunityBtn: "Сменить",
        communitiesNews: "События",
        reject: "Отозвать",
        apply: "Принять",
        courtMessage1: "Вы желаете присоединиться к ",
        courtMessage2: " но ваша заявка еще не одобрена",
        joinMessage1: " желает присоединиться к сообществу ",
        joinMessage2: ". Вы можете одобрить или отклонить заявку",
        menuChangeCommunity: "изменить",
        menuSettings: "Настройки",
        menuSelectEnding: "Окончания",
        menuSelectLanguage: "Язык",
        communityRating: "Рейтинг",
        communityCourted: "Ваша заявка принята. Ждите одобрения.",
        userOwner: "Основатель",
        userReferee: "Судья",
        userPlayer: "Игрок",
        menuMarkerView: "Табло",
        menuCommunityEvents: "События",
        createCommunityEvent: "Название события",
        createCommunityEventBtn: "Создать",
        menuCommunityEventsNew: "Создать событие",
        communityEventCreated: "Событие создано",
        activeEvent: "Активно",
        inactiveEvent: "Завершенный"

    }

};