var languages = {
    "en": {
        flag: "flag-GB",
        language: "English",
        menuNoStartSwap: "Maiden first",
        menuEventName: "Event name",
        menuFirstPlayer: "First ",
        menuSecondPlayer: "Second ",
        menuGame: "Game ",
        menuSets: "Sets ",
        menuLegs: "Legs ",
        menuNewGame: "New Game",
        menuContinue: "Continue",
        menuHistory: "History",
        historyTotal: "Total: ",
        menuMenu: "Close",
        histoyTotal: "Total: ",
        keyboardMenu: "M",
        keyboardOk: "Ok",
        set: "Set ",
        leg: "Leg ",
        sets: "Sets",
        legs: "Legs",
        bannerInstallSmall: "Install",
        bannerInstall: "Install Application",
        bannerDescription: "Add the Darts Forge application to your home screen",
        menuProfile: "Profile",
        menuPublicKey: "Public key",
        menuPrivateKey: "Private key",
        menuLoginSignin: "Log In | Sign In",
        menuLogout: "Log Out",
        menuSelectCommunity: "Select Community",
        menuInCommunity: " at ",
        communities: "Communities: ",
        refresh: "Refresh",
        createCommunity: "Create community",
        createCommunityBtn: "Create",
        createCommunityCity: "City",
        createCommunityName: "Community Name",
        changeCommunity: "Change community",
        courtCommunity: "Court the community",
        selectCommunityName: "Select community",
        courtCommunityBtn: "Court",
        ownedCommunities: "Your communities",
        joinedCommunities: "Joined communities",
        courtedCommunities: "Waiting agreement",
        communityCreated: "Community created!",
        changeCommunityBtn: "Change",
        communitiesNews: "Events",
        reject: "Reject",
        apply: "Apply",
        courtMessage1: "You courted the ",
        courtMessage2: ". Waiting approovement",
        joinMessage1: " wants to join to the ",
        joinMessage2: ".",
        menuChangeCommunity: "change",
        menuSettings: "Settings",
        menuSelectEnding: "Endings",
        menuSelectLanguage: "Language",
        communityRating: "Rating",
        communityCourted: "You courted the community. Wait approovement please.",
        userOwner: "Secretary",
        userReferee: "Referee",
        userPlayer: "Player",
        menuMarkerViewOn: "Marker on",
        menuMarkerViewOff: "Marker off",
        menuCommunityEvents: "Events",
        createCommunityEvent: "Event name",
        createCommunityEventBtn: "Create",
        menuCommunityEventsNew: "Create new event",
        communityEventCreated: "Event created",
        activeEvent: "Active",
        inactiveEvent: "Finished",
        publishGame: "Publish game",
        publishWin: "The game is done. Won ",
        publishGameBtn: "Publish",
        publishGameUndoBtn: "Undo",
        menuInGame: "Game",
        noEvents: "Currently there is nothing for you",
        highestClose: "Highest close: ",
        t60: "60+",
        t100: "100+",
        t140: "140+",
        t180: "180",
        weeklyRating: "Your weekly stats",
        opened: "Opened",
        eventName: "Name",
        menuEventGame: "Community game",
        menuEvent: "Community",
        deleteGame: "Delete the game",
        deleteEmptyEvent: "Delete empty event",
        deleteEmptyCommunity: "Delete empty community",
        delete: "Delete",
        repeat: "Repeat",
        notPublished: " Game wasn't published. ",
        gameLengthError: "You can't continue the game due to the game length was changed.",
        gameSetError: "The game can't be continued. The game is too far from sets limit you choose.",
        gameLegError: "The game can't be continued. The game is too far from legs limit you choose.",
        gamenoStartSwapError: "You are late to change player sex.",
        fileExportTXT: "File export to TXT",
        fileExportCSV: "File export to CSV",
        messageReject1: " join to the community ",
        messageReject2: " rejected.",
        messageReject3: " withdraw the application to ",
        messageJoin: " joined the community ",
        messageEventCreated: " event created.",
        messageEventDeleted: " event deleted.",
        menuTargetNumber: "Target #",
        menuSetupCamera: "Setup camera",
        audioSource: "Audio source",
        targetSource: "Target source",
        portraitSource: "Portrait source",
        recorderResolution: "Resolution",
        toggleMicOn: "Enable voice recognition",
        toggleMicOff: "Disable voice recognition",
    },
    "ru": {
        flag: "flag-RU",
        language: "Русский",
        menuNoStartSwap: "Maiden first",
        menuEventName: "Событие",
        menuFirstPlayer: "Первый ",
        menuSecondPlayer: "Второй ",
        menuGame: "Игра ",
        menuSets: "Сетов ",
        menuLegs: "Легов ",
        menuNewGame: "Новая игра",
        menuContinue: "Продолжить",
        menuHistory: "История",
        historyTotal: "Итого: ",
        menuMenu: "Закрыть",
        histoyTotal: "Всего: ",
        keyboardMenu: "М",
        keyboardOk: "Ok",
        set: "Сет ",
        leg: "Лег ",
        sets: "Sets",
        legs: "Legs",
        bannerInstallSmall: "Установить",
        bannerInstall: "Установить приложение",
        bannerDescription: "Добавить приложение Darts Forge на рабочий стол",
        menuProfile: "Профиль",
        menuPublicKey: "Публичный ключ",
        menuPrivateKey: "Секретный ключ",
        menuLoginSignin: "Войти",
        menuLogout: "Выйти",
        menuSelectCommunity: "Выберите Сообщество",
        menuInCommunity: " в ",
        communities: "Сообщества: ",
        refresh: "Обновить",
        createCommunity: "Создать сообщество",
        createCommunityBtn: "Создать",
        createCommunityCity: "Город",
        createCommunityName: "Название",
        changeCommunity: "Сменить сообщество",
        courtCommunity: "Вступить в сообщество",
        selectCommunityName: "Выберите сообщество",
        courtCommunityBtn: "Вступить",
        ownedCommunities: "Ваши сообщества",
        joinedCommunities: "Одобренные сообщества",
        courtedCommunities: "Ожидают одобрения",
        communityCreated: "Сообщество создано!",
        changeCommunityBtn: "Сменить",
        communitiesNews: "События",
        reject: "Отозвать",
        apply: "Принять",
        courtMessage1: "Заявка в ",
        courtMessage2: " ожидает одобрения",
        joinMessage1: " желает присоединиться к сообществу ",
        joinMessage2: ".",
        menuChangeCommunity: "изменить",
        menuSettings: "Настройки",
        menuSelectEnding: "Окончания",
        menuSelectLanguage: "Язык",
        communityRating: "Рейтинг",
        communityCourted: "Ваша заявка принята. Ждите одобрения.",
        userOwner: "Секретарь",
        userReferee: "Рефери",
        userPlayer: "Игрок",
        menuMarkerViewOn: "Табло включить",
        menuMarkerViewOff: "Табло выключить",
        menuCommunityEvents: "События",
        createCommunityEvent: "Название события",
        createCommunityEventBtn: "Создать",
        menuCommunityEventsNew: "Создать событие",
        communityEventCreated: "Событие создано",
        activeEvent: "Активно",
        inactiveEvent: "Завершено",
        publishGame: "Опубликовать результаты",
        publishWin: "Игра завершена. Победитель ",
        publishGameBtn: "Опубликовать",
        publishGameUndoBtn: "Отменить",
        menuInGame: "Игра",
        noEvents: "На данный момент для вас ничего нет",
        highestClose: "Наибольшее закрытие: ",
        t60: "60+",
        t100: "100+",
        t140: "140+",
        t180: "180",
        weeklyRating: "Статистика по неделям",
        opened: "Создано",
        eventName: "Название",
        menuEventGame: "История",
        menuEvent: "Событие",
        deleteGame: "Удалить игру",
        deleteEmptyEvent: "Удалить пустое событие",
        deleteEmptyCommunity: "Удалить пустое сообщество",
        delete: "Удалить",
        repeat: "Повторить",
        notPublished: " Игра не была опубликована. ",
        gameLengthError: "Невозможно изменить тип уже начатой игры.",
        gameSetError: "Игра не может быть продолжена. Игра зашла дальше чем вы выставили ограничение по сетам.",
        gameLegError: "Игра не может быть продолжена. Игра зашла дальше чем вы выставили ограничение по легам.",
        gamenoStartSwapError: "Уже поздно менять пол игрока.",
        fileExportTXT: "Сохранить в файл TXT",
        fileExportCSV: "Сохранить в файл CSV",
        messageReject1: " заявка в ",
        messageReject2: " отклонена.",
        messageReject3: " отозвал заявку в ",
        messageJoin: " присоединился к сообществу ",
        messageEventCreated: " событие создано.",
        messageEventDeleted: " событие удалено.",
        menuTargetNumber: "Мишень №",
        menuSetupCamera: "Настройка камер",
        audioSource: "Микрофон",
        targetSource: "Камера на мишень",
        portraitSource: "Камера на игрока",
        recorderResolution: "Разрешение",
        toggleMicOn: "Включить распознование речи",
        toggleMicOff: "Выключить распознование речи",
    }

};